events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;
        server_name localhost;
        root /app; # Répertoire par défaut dans Nixpacks/Coolify
        index index.html;

        # Compression Gzip pour accélérer le chargement du CSS
        gzip on;
        gzip_types text/plain text/css application/javascript;

        location / {
            try_files $uri $uri/ =404;
        }

        # Cache agressif pour les assets (CSS, images)
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
            expires 1y;
            add_header Cache-Control "public, no-transform";
        }
    }
}